### ISSUE TITLE
Display live sample data

### ISSUE THREAD

**Issue by rappen** [Innofactor/XrmToolBox.Plugins#16]
When designing a view, getting sample data in the grid would help finding the best column widths and order.
Add option to retrieve information from CRM to display the view by using the view's fetchxml.

**Comment by mscottsewell** [comment]
I came here to suggest this - but you've beaten me to it. - so I'll just leave a +1 here. Thanks!

**Comment by rappen** [comment]
Issue moved to [Innofactor/XrmToolBox.ViewDesigner #1](https://github.com/Innofactor/XrmToolBox.ViewDesigner/issues/1) via [**ZenHub**](https://www.zenhub.com/)
