### ISSUE TITLE
Can't see the Saved View Layout XML

### ISSUE THREAD

**Issue by nzhome** [Innofactor/XrmToolBox.Plugins#20]
I get a lot of errors to do with the LayoutXML when saving fetch queries, and there is no tool that can see and edit the advanced find savedquery layout xml.   I picked up via google that your sourcecode has something fairly close.  Can you please add a way to see the layout XML via FetchXML Builder. thanks.
    https://github.com/Cinteros/XrmToolBox.Plugins/blob/master/Cinteros.Xrm/Common/Forms/SelectViewDialog.cs
qex.ColumnSet = new ColumnSet("name", "returnedtypecode", "fetchxml", "layoutxml");
txtFetch.Text = ((ViewItem)cmbView.SelectedItem).GetLayout();

**Comment by nzhome** [comment]
Found it.  under the View Layout Replicator plugin.  double click a view row to display its layout xml.

Now I just need a way to Update the view with the new layout and new fetch xml that I made.  

and even better would be a preview tool that can take the fetch xml and layout xml and process it on the server to test it faster than uploading, going into crm refreshing the screen, see an error, go back make a change, run again. that development process is too slow.  need a way to update the fetchxml and layoutxml and press validate and see the result.

**Comment by nzhome** [comment]
Also I created a couple of public system views that are corrupt, and I don't want to deactivate them, I want to delete them..  where is the tool in xrmtoolbox that allows me to fully delete a corrupt view, or sometimes I created a duplicate View that I just want to delete forever without getting it back!

**Comment by rappen** [comment]
Issue moved to [Innofactor/XrmToolBox.ViewDesigner #4](https://github.com/Innofactor/XrmToolBox.ViewDesigner/issues/4) via [**ZenHub**](https://www.zenhub.com/)
