### ISSUE TITLE
View Designer - suggestions

### ISSUE THREAD

**Issue by polshgiant** [Innofactor/XrmToolBox.Plugins#27]
The View Designer is a great tool, thanks very much for the contribution.  I have some suggestions that I feel would increase its usability:

- It would be great if there was an entity selector at the top and then a pane on the left of the grid area showing all views for that entity.  The idea being once I choose an entity, I'd like to be one click away from choosing a different view on the same entity.  Using the Open button is really tedious.  At the very least, if the open button could default to selecting the entity and the view that I am currently on, that would be much better.
- Option to toggle between display names and schema name of columns
- Small buttons on column headers to quickly remove columns
- It would be amazing if the tool was enhanced to support bulk operations.  Some examples of functions that would be super useful and time-saving:
  - Add a column
    - Choose which views explicitly
    - Or option to do it for any view that has the column
  - Change width of a column 
    - Choose which views explicitly
    - Or option to do it for any view that has the column
  - Replace a column with a different column
    - Choose which views explicitly
    - Or option to do it for any view that has the column

Thoughts?

**Comment by rappen** [comment]
Issue moved to [Innofactor/XrmToolBox.ViewDesigner #12](https://github.com/Innofactor/XrmToolBox.ViewDesigner/issues/12) via [**ZenHub**](https://www.zenhub.com/)
