### ISSUE TITLE
Bulk Data Updater: text box which accepts new value should allow new lines

### ISSUE THREAD

**Issue by polshgiant** [Innofactor/XrmToolBox.Plugins#31]
Currently, only single line values can be pasted into the textbox in step 3.  It would be helpful if the box could be configured to accept new line characters.

**Comment by rappen** [comment]
Issue moved to [Innofactor/XrmToolBox.BulkDataUpdater #11](https://github.com/Innofactor/XrmToolBox.BulkDataUpdater/issues/11) via [**ZenHub**](https://www.zenhub.com/)
