### ISSUE TITLE
View Designer: Display values from related records in the Live Preview

### ISSUE THREAD

**Issue by mscottsewell** [Innofactor/XrmToolBox.Plugins#33]
Currently, values from linked entities are not displayed in the live preview. I want them. :)

**Comment by mscottsewell** [comment]
Also values from 'two-option' fields and multi-select option sets are not shown.

**Comment by rappen** [comment]
Issue moved to [Innofactor/XrmToolBox.ViewDesigner #10](https://github.com/Innofactor/XrmToolBox.ViewDesigner/issues/10) via [**ZenHub**](https://www.zenhub.com/)
