### ISSUE TITLE
Bulk Data Updater crashes on startup

### ISSUE THREAD

**Issue by jrichview** [Innofactor/XrmToolBox.Plugins#34]
Error notification attached.
![capture](https://user-images.githubusercontent.com/2236908/37218900-bb4ae9a8-23b9-11e8-9b3f-e0c2b697b617.JPG)

Your download package seems to not include this DLL.

**Comment by anuarn** [comment]
Hi. I have the same issue. It would be great to have this feature working.

**Comment by rappen** [comment]
Can you check if this file exists, and which version it has?
``c:\Users\<username>\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\Cinteros.Xrm.CRMWinForm.dll``

**Comment by jrichview** [comment]
![capture](https://user-images.githubusercontent.com/2236908/37464196-8a1e38f4-284f-11e8-8793-4c41d1fdb514.JPG)
As you will see from this img, I don't have that file in that folder at all. However, the app is working at the moment. I downloaded your latest and stuck the DLLs in the XRMToolBox folder.  That seemed to get me going. Interestingly, the CRMWinForm.dll is also not in that folder.

**Comment by rappen** [comment]
Interesting it is!
Thanks for sharing the workaround.
I hope to find time to release a new version of BDU in the near future, primarily to implement this feature: https://github.com/Innofactor/XrmToolBox.BulkDataUpdater/issues/9
But the handling of dependent assemblies will also be addressed.

**Comment by rappen** [comment]
@jrichview @anuarn I would love some feedback how the new version (1.2018.4.1) works, if it has the same problems?

**Comment by rappen** [comment]
Issue moved to [Innofactor/XrmToolBox.BulkDataUpdater #10](https://github.com/Innofactor/XrmToolBox.BulkDataUpdater/issues/10) via [**ZenHub**](https://www.zenhub.com/)
